# Generated by Django 5.0.7 on 2025-01-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='phone',
        ),
        migrations.AddField(
            model_name='registration',
            name='phone_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
