# Generated by Django 5.0.7 on 2025-01-06 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registration_user_alter_registration_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='location',
            field=models.CharField(choices=[('location_a', 'Manzil A'), ('location_b', 'Manzil B')], default='location_a', max_length=20, verbose_name='Manzil'),
        ),
    ]
