# Generated by Django 5.0.7 on 2025-01-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_registration_created_at_registration_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='Ism_Familyangiz',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='reason',
            new_name='Navbat_olishning_sababi',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='created_at',
            new_name='Navbatga_yozilgan_vaqt',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='phone_number',
            new_name='Telefon_raqamingiz',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='location',
        ),
        migrations.AddField(
            model_name='registration',
            name='Manzil',
            field=models.CharField(choices=[('🏥 Манзил: Маргилон шахар (комбинат ) 6-поликлиника 61-хона 3-кават🕛 кабул вакти 14:00дан 17:00гача.', '🏥 Манзил: Маргилон шахар (комбинат ) 6-поликлиника 61-хона 3-кават🕛 кабул вакти 14:00дан 17:00гача.'), ('🏥 Манзил: Сой буйи Дилобар медикал (шахар болалар шифохонаси ёнида)🕛 кабул вакти 18:30 дан 20: 30 гача.', '🏥 Манзил: Сой буйи Дилобар медикал (шахар болалар шифохонаси ёнида)🕛 кабул вакти 18:30 дан 20: 30 гача.')], default='🏥 Манзил: Маргилон шахар (комбинат ) 6-поликлиника 61-хона 3-кават🕛 кабул вакти 14:00дан 17:00гача.', max_length=2000, verbose_name='Manzilni tanlang'),
        ),
    ]
