# Generated by Django 5.0.7 on 2025-01-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
