# Generated by Django 5.0.7 on 2025-01-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Manzil',
            field=models.CharField(choices=[('🏥 Манзил: Маргилон шахар', '🏥 Манзил: Маргилон шахар (комбинат ) 6-поликлиника 61-хона 3-кават🕛 кабул вакти 14:00дан 17:00гача.'), ('🏥 Манзил: Сой буйи Дилобар медикал', '🏥 Манзил: Сой буйи Дилобар медикал (шахар болалар шифохонаси ёнида)🕛 кабул вакти 18:30 дан 20: 30 гача.')], default='🏥 Манзил: Маргилон шахар', max_length=2000, verbose_name='Manzilni tanlang'),
        ),
    ]
